Time-out ping check after 5s
Add script for timeout
Compile man-pages
Use shebang in header of org files to tangle

diff --git a/bin/waystart b/bin/waystart
--- a/bin/waystart
+++ b/bin/waystart
@@ -18,9 +18,6 @@
 # You should have received a copy of the GNU General Public License
 # along with Prady_runcom.  If not, see <https://www.gnu.org/licenses/>.
 
-# shellcheck disable=SC1091
-. "${RUNCOMDIR:-${HOME}/.runcom}/bin/common.sh" || exit 1
-
 set_vars() {
     unset DBUS_SESSION_BUS_ADDRESS
     unset SESSION_MANAGER
@@ -66,13 +63,30 @@ cli_args () {
     fi
 }
 
+parse_desktop_entry () {
+    client="${1}"
+    if [ ! -f "${client}" ]; then
+        if [ "$(dirname "${client}")" = '.' ]; then
+            client="/usr/share/wayland-sessions/${client}"
+        else
+            echo "Bad wayland session: ${client}." >&2
+            exit 1
+        fi
+    fi
+    exec_line="$(grep -i "^exec" ${client} | head -1)"
+    if [ -z "${exec_line}" ]; then
+        exec_line="$(grep -i "^tryexec" ${client} | head -1)"
+    fi
+    exec_cmd="${exec_line#*=}"
+    unset desk_line
+}
 parse_initrc () {
     # $1 wayinitrc file path
     file_is_exec=true
     while read -r init_line; do
         if [ ! "${init_line%.desktop}" = "${init_line}" ]; then
             file_is_exec=false
-            parse_desktop_entry "${init_line}" "wayland-"
+            parse_desktop_entry "${init_line}"
             break
         fi
     done<"${1}"
@@ -87,17 +101,17 @@ parse_client () {
            || [ -x "${client}" ]; then
         exec_cmd="${client}"
     elif [ ! "${client%.desktop}" = "${client}" ]; then
-        parse_desktop_entry "${client}" "wayland-"
+        parse_desktop_entry "${client}"
     else
         # parse it to locate .desktop entry if available
         parse_initrc "${client}"
     fi
     if [ -z "${exec_cmd}" ]; then
-        clean_exit 1 "Couldn't find session executable for ${client}."
+        echo "Couldn't find session executable for ${client}."
+        exit 1
     fi
 }
-
-unset_vars () {
+clean_up () {
     unset client
     unset userclientrc
     unset sysclientrc
@@ -117,6 +131,7 @@ main () {
     # shellcheck disable=SC2086
     dbus-run-session ${exec_cmd} ${clientargs}
     exit_code=$?
-    clean_exit $exit_code
+    clean_up
+    exit $exit_code
 }
 main "$@"
